"""
RS-8 O-3 — Dutch NL Quality Evaluation
========================================
Takes the EN dialogue trees from O-2, sends them to GPT-4.1-mini for Dutch
translation, evaluates completeness + Flesch-Douma readability, and surfaces
5 spot-check utterances for human review.

Usage:
    cd tools
    uv run --with python-dotenv python rs8/o3_nl_quality.py

Outputs:
    tools/rs8/outputs/o3/{tree_name}_bilingual.json  — EN+NL merged trees
    tools/rs8/outputs/o3/o3_report.json              — FD scores + gate results
    tools/rs8/outputs/o3/o3_spot_check.md            — 5 utterances for human review

Preconditions:
    tools/.env: OPENAI_API_KEY=sk-...
    tools/rs8/outputs/o2/gpt-4.1-mini/ contains the trees generated by O-2
"""

from __future__ import annotations

import json
import os
import re
import sys
import time
from pathlib import Path

ENV_FILE = Path(__file__).parent.parent / ".env"
if ENV_FILE.exists():
    from dotenv import load_dotenv
    load_dotenv(ENV_FILE)

import openai

import sys as _sys
if hasattr(_sys.stdout, 'reconfigure'):
    _sys.stdout.reconfigure(encoding='utf-8', errors='replace')
    _sys.stderr.reconfigure(encoding='utf-8', errors='replace')

O2_DIR = Path(__file__).parent / "outputs" / "o2" / "gpt-4.1-mini"
OUT_DIR = Path(__file__).parent / "outputs" / "o3"
OUT_DIR.mkdir(parents=True, exist_ok=True)

# Translation model — mini is fine for this task (fluent EN→NL)
TRANSLATE_MODEL = "gpt-4.1-mini"

TRANSLATE_SYSTEM = """You are a bilingual Dutch/English translator specialising in children's
fantasy dialogue for ages 5–8.

TASK: Translate the given JSON dialogue tree from English to Dutch.

RULES:
1. Add a "nl" key alongside every existing "en" key inside:
   - characterLine: { "en": "...", "nl": "..." }
   - playerLabel:   { "en": "...", "nl": "..." }
2. Dutch must be idiomatic and natural — NOT a word-for-word translation.
3. Register: informal, warm, child-appropriate ("jij/jou", not "u").
4. Keep all punctuation and sentence rhythm similar.
5. Do NOT change any other fields (nodeId, tone, branches, outcome, etc.).
6. Return the complete JSON tree with added nl fields. No markdown fences, no commentary.
"""


# ---------------------------------------------------------------------------
# Flesch-Douma readability
# ---------------------------------------------------------------------------

def _count_syllables_nl(word: str) -> int:
    """Dutch syllable count approximation (vowel groups)."""
    word = word.lower().strip(".,!?\"'")
    if not word:
        return 0
    vowels   = "aeiouy"
    count    = 0
    in_vowel = False
    for ch in word:
        if ch in vowels:
            if not in_vowel:
                count += 1
            in_vowel = True
        else:
            in_vowel = False
    # Dutch diphthongs heuristic: don't subtract silent e (different from EN)
    return max(1, count)


def flesch_douma(text: str) -> float:
    """
    Flesch-Douma grade for Dutch:
        FD = 206.84 − (77.0 × syllables_per_word) − (0.93 × words_per_sentence)
    Target: FD ≥ 70 (very easy, age 7+)
    """
    sentences = re.split(r'[.!?]+', text)
    sentences = [s.strip() for s in sentences if s.strip()]
    words     = re.findall(r"\b[a-zA-ZàáâäèéêëìíîïòóôöùúûüÀ-ÿ']+\b", text)
    if not sentences or not words:
        return 0.0
    syllables = sum(_count_syllables_nl(w) for w in words)
    asw = syllables / len(words)
    asl = len(words) / len(sentences)
    fd  = 206.84 - (77.0 * asw) - (0.93 * asl)
    return round(fd, 2)


# ---------------------------------------------------------------------------
# Translation
# ---------------------------------------------------------------------------

def translate_tree(client: openai.OpenAI, tree: dict) -> tuple[dict | None, dict]:
    t0 = time.perf_counter()
    try:
        response = client.chat.completions.create(
            model=TRANSLATE_MODEL,
            messages=[
                {"role": "system", "content": TRANSLATE_SYSTEM},
                {"role": "user",   "content": json.dumps(tree, ensure_ascii=False)},
            ],
            response_format={"type": "json_object"},
            temperature=0.3,     # lower temp for more consistent translation
            max_tokens=3000,
        )
        latency_ms = round((time.perf_counter() - t0) * 1000)
        raw   = response.choices[0].message.content or ""
        usage = response.usage
        in_t  = usage.prompt_tokens     if usage else 0
        out_t = usage.completion_tokens if usage else 0
        cost  = (in_t / 1_000_000) * 0.40 + (out_t / 1_000_000) * 1.60  # mini rates

        try:
            translated = json.loads(raw)
        except json.JSONDecodeError as e:
            return None, {"latency_ms": latency_ms, "in_tokens": in_t, "out_tokens": out_t,
                          "cost_usd": round(cost, 6), "error": str(e)}

        return translated, {"latency_ms": latency_ms, "in_tokens": in_t, "out_tokens": out_t,
                            "cost_usd": round(cost, 6), "error": None}
    except Exception as exc:
        return None, {"latency_ms": round((time.perf_counter() - t0) * 1000),
                      "in_tokens": 0, "out_tokens": 0, "cost_usd": 0.0, "error": str(exc)}


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------

def validate_bilingual(en_tree: dict, nl_tree: dict) -> dict:
    """Check completeness and measure FD scores."""
    en_node_ids = {n["nodeId"] for n in en_tree.get("nodes", [])}
    nl_node_ids = {n["nodeId"] for n in nl_tree.get("nodes", [])}
    missing_ids = en_node_ids - nl_node_ids

    # Collect all NL text
    nl_char_lines = []
    nl_player_labels = []
    missing_nl_fields = []
    for n in nl_tree.get("nodes", []):
        cl = n.get("characterLine", {})
        if "nl" not in cl:
            missing_nl_fields.append(f"{n['nodeId']}.characterLine.nl")
        else:
            nl_char_lines.append(cl["nl"])
        for br in n.get("branches", []):
            pl = br.get("playerLabel", {})
            if "nl" not in pl:
                missing_nl_fields.append(f"{n['nodeId']}.{br['branchId']}.playerLabel.nl")
            else:
                nl_player_labels.append(pl["nl"])

    all_nl_text = " ".join(nl_char_lines + nl_player_labels)
    fd_score = flesch_douma(all_nl_text)

    completeness_ok = len(missing_ids) == 0 and len(missing_nl_fields) == 0
    fd_ok = fd_score >= 70.0

    return {
        "completeness_ok": completeness_ok,
        "missing_node_ids": sorted(missing_ids),
        "missing_nl_fields": missing_nl_fields[:5],
        "fd_score": fd_score,
        "fd_ok": fd_ok,
        "overall_pass": completeness_ok and fd_ok,
    }


# ---------------------------------------------------------------------------
# Spot-check selection (5 utterances most varied by tone)
# ---------------------------------------------------------------------------

def pick_spot_check_utterances(tree: dict, n: int = 5) -> list[dict]:
    """Pick n representative utterances: prefer varied tones and non-trivial length."""
    candidates = []
    for node in tree.get("nodes", []):
        cl = node.get("characterLine", {})
        if cl.get("en") and cl.get("nl"):
            candidates.append({
                "nodeId":  node["nodeId"],
                "type":    "characterLine",
                "tone":    node.get("tone", "?"),
                "en":      cl["en"],
                "nl":      cl["nl"],
            })
        for br in node.get("branches", []):
            pl = br.get("playerLabel", {})
            if pl.get("en") and pl.get("nl"):
                candidates.append({
                    "nodeId":  node["nodeId"],
                    "type":    "playerLabel",
                    "tone":    node.get("tone", "?"),
                    "en":      pl["en"],
                    "nl":      pl["nl"],
                })
    # Sort by EN length descending (longer = more informative spot-check), deduplicate tones
    seen_tones: set[str] = set()
    picked = []
    for c in sorted(candidates, key=lambda x: -len(x["en"])):
        if len(picked) >= n:
            break
        if c["tone"] not in seen_tones or len(picked) < n:
            picked.append(c)
            seen_tones.add(c["tone"])
    return picked[:n]


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    api_key = os.environ.get("OPENAI_API_KEY", "").strip().strip('"').strip("'")
    if not api_key:
        print("ERROR: OPENAI_API_KEY not set.", file=sys.stderr)
        sys.exit(1)

    client = openai.OpenAI(api_key=api_key)

    # Load O-2 trees (gpt-4.1-mini — the chosen model)
    tree_files = sorted(O2_DIR.glob("tree_*.json"))
    if not tree_files:
        print(f"ERROR: No tree files found in {O2_DIR}", file=sys.stderr)
        sys.exit(1)

    all_results = []
    all_spot_checks: list[dict] = []
    total_cost = 0.0

    for tree_file in tree_files:
        print(f"\n{'='*55}")
        print(f"Translating: {tree_file.name}")
        en_tree = json.loads(tree_file.read_text(encoding="utf-8"))
        print(f"  Sending {len(en_tree['nodes'])} nodes to {TRANSLATE_MODEL}...", end="", flush=True)

        nl_tree, meta = translate_tree(client, en_tree)
        total_cost += meta.get("cost_usd", 0.0)

        if nl_tree is None:
            print(f" ❌ ERROR: {meta.get('error')}")
            all_results.append({"file": tree_file.name, "error": meta.get("error"), "meta": meta})
            continue

        print(f" ✅ ({meta['latency_ms']} ms, {meta['in_tokens']}in/{meta['out_tokens']}out, ${meta['cost_usd']:.5f})")

        # Validate
        val = validate_bilingual(en_tree, nl_tree)
        print(f"  FD score: {val['fd_score']} {'✅' if val['fd_ok'] else '❌'} (target ≥70)")
        print(f"  Completeness: {'✅' if val['completeness_ok'] else '❌'}")
        if val["missing_nl_fields"]:
            print(f"    Missing NL fields: {val['missing_nl_fields'][:3]}")

        # Save bilingual tree
        out_name  = tree_file.stem + "_bilingual.json"
        out_file  = OUT_DIR / out_name
        out_file.write_text(json.dumps(nl_tree, indent=2, ensure_ascii=False), encoding="utf-8")
        print(f"  Saved: {out_name}")

        # Collect spot checks
        spots = pick_spot_check_utterances(nl_tree, n=5)
        all_spot_checks.extend(spots[:3])  # max 3 per tree, select 5 total at end

        all_results.append({
            "file":       tree_file.name,
            "meta":       meta,
            "validation": val,
            "error":      None,
        })

    # ---------------------------------------------------------------------------
    # Summary
    # ---------------------------------------------------------------------------
    print(f"\n{'='*55}")
    print("O-3 SUMMARY")
    print(f"{'='*55}")
    passed = sum(1 for r in all_results if r.get("validation", {}).get("overall_pass"))
    print(f"  Trees translated: {len(all_results)}")
    print(f"  Trees passing all NL gates: {passed}/{len(all_results)}")
    print(f"  Total translation cost: ${total_cost:.5f}")

    fd_scores = [r["validation"]["fd_score"] for r in all_results if "validation" in r]
    if fd_scores:
        print(f"  Flesch-Douma scores: {fd_scores} (avg {round(sum(fd_scores)/len(fd_scores),1)})")

    overall = passed == len(all_results) and len(all_results) > 0
    print(f"\nO-3 GATE: {'PASS ✅ — O-8 BILINGUAL SPRINT UNBLOCKED' if overall else 'FAIL ❌ — review FD scores and completeness'}")

    # ---------------------------------------------------------------------------
    # Spot-check MD
    # ---------------------------------------------------------------------------
    spot_sample = all_spot_checks[:5]
    md = ["# RS-8 O-3 — Dutch Spot-Check", "",
          f"**Date:** {time.strftime('%Y-%m-%d')}  ",
          f"**Model:** {TRANSLATE_MODEL}  ",
          "",
          "Please review the 5 utterances below for:",
          "- Natural, idiomatic Dutch (not literal translation)",
          "- Informal register ('jij/jou', not 'u')",
          "- Age-appropriate vocabulary (7-year-old level)",
          "",
          "| # | EN | NL | Tone | Type |",
          "|---|---|---|---|---|"]
    for i, s in enumerate(spot_sample, 1):
        md.append(f"| {i} | {s['en']} | {s['nl']} | {s['tone']} | {s['type']} |")

    md += ["", "**Verdict (fill in):** ✅ PASS / ❌ FAIL", "",
           "> If FAIL: note which utterances are problematic and why. Agent will refine prompt and re-run."]

    spot_md = OUT_DIR / "o3_spot_check.md"
    spot_md.write_text("\n".join(md), encoding="utf-8")

    # JSON report
    report = {
        "overall_pass": overall,
        "model":        TRANSLATE_MODEL,
        "total_cost":   round(total_cost, 6),
        "results":      all_results,
        "spot_checks":  spot_sample,
    }
    (OUT_DIR / "o3_report.json").write_text(
        json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8"
    )

    print(f"\n✅ Reports written to {OUT_DIR}/")
    print(f"   o3_report.json, o3_spot_check.md")
    print(f"\n>>> HUMAN REVIEW REQUIRED: open o3_spot_check.md and verify the 5 Dutch utterances.")


if __name__ == "__main__":
    main()
